### ISSUE TITLE
Limited to 2^31 nodes

### ISSUE THREAD

**Issue by systemed** [simonpoole/mapsplit#15]
Currently (February 2021) the Geofabrik Europe extract is 2710803032 nodes, which is more than 2^31. Mapsplit consequently can't split it.

**Comment by simonpoole** [comment]
This was resolved in release 4.0. There is still a fairly arbitrary limitation in that the number of elements that have to be copied to more than nearby tiles https://github.com/simonpoole/mapsplit/issues/30 but a solution to that is in the works.
